export const RECYCLING_CENTERS = [
  // Negombo / Gampaha / Nearby (High priority for you)
  { name: "Negombo Recycling Club (NRC)", lat: 6.75, lng: 80.05, desc: "Advanced plastic recycling (HDPE, PP, PS, ABS); integrated washing/compounding; Milleniya, Horana but serves Negombo/coastal areas" },
  { name: "Vass Enterprises", lat: 7.20, lng: 79.83, desc: "Plastic containers; No.799, Chilaw Road, Kattuwa, Negombo" },
  { name: "Berny Lanka Services", lat: 7.17, lng: 79.88, desc: "Plastic recycling; No.217, Welabada Road, Katunayake (near airport)" },
  { name: "Polygun Poly Recycling (Pvt) Ltd", lat: 6.99, lng: 79.89, desc: "Polythene/plastic; 315, Negombo Road, Wattala" },
  { name: "Plas Techs (Pvt) Ltd", lat: 6.99, lng: 79.89, desc: "PVC, PS, ABS, LDPE; Negombo Road areas / Wattala" },
  { name: "Apex Plastics", lat: 7.03, lng: 79.92, desc: "Plastic recycling; 7 A/1, Horape, Ragama" },
  { name: "Emareld Industries", lat: 7.03, lng: 79.92, desc: "Plastic recycling; 181/A, Peralanda, Ragama" },
  { name: "Lanka Recycling & Environment Service", lat: 7.03, lng: 79.92, desc: "PVC, PS, ABS, LDPE; No.137/1, Lanka Matha Road, Mahabage, Ragama" },
  { name: "Sha Plastic", lat: 7.03, lng: 79.92, desc: "Plastic; No.47, C.W.Waththa, Magulpokuna, Ragama" },
  { name: "Ja-Ela / Kotugoda collections (various)", lat: 7.077, lng: 79.891, desc: "General waste & plastics; local near Negombo (e.g., M.W.Sunil Premawansa Silva, Kurusawatta, Kotugoda)" },

  // Western Province - Colombo & Surrounds (Majority from CEA lists)
  { name: "A P International", lat: 6.87, lng: 79.99, desc: "PET, PP, HIPS, HDPE, LDPE, iron, aluminium, tin, paper, glass, cardboard; Athurugiriya" },
  { name: "Viridis (Pvt) Ltd", lat: 6.935, lng: 80.058, desc: "PET, PP, PC, HDPE, LDPE; crushed/exported; Templeburg Zone, Homagama/Panagoda" },
  { name: "Poly-Cycle (Pvt) Ltd", lat: 6.935, lng: 79.925, desc: "LDPE, HDPE; pellets; Mulleriyawa/Angoda" },
  { name: "Green Lanka Recycling Private Limited", lat: 6.843, lng: 79.885, desc: "HDPE, LDPE, LLDPE; pellets; Ratmalana" },
  { name: "Cristal Plastics (PVT) Ltd", lat: 6.85, lng: 79.87, desc: "PP, HIPS, HDPE, LDPE; Dehiwala" },
  { name: "Sachitha Plastic Manufacture", lat: 6.935, lng: 80.058, desc: "PP; pellets/household items; Panagoda" },
  { name: "Ciyasa Plastics", lat: 6.94, lng: 79.98, desc: "PVC, PP, ABS, PC, HDPE, LDPE; granules/crush; Kaduwela/Korathota" },
  { name: "Dot Line Packaging", lat: 6.87, lng: 79.99, desc: "HDPE, LDPE; Athurugiriya/Oruwala" },
  { name: "M & D Plastic and Polymer Company", lat: 6.77, lng: 79.88, desc: "HDPE, LDPE; pellets/polythene film; Moratuwa" },
  { name: "J.S Recycle Polythene", lat: 6.95, lng: 80.35, desc: "HDPE, LDPE; polythene for concrete; Kosgama" },
  { name: "EMP PVC Technology (Pvt) Ltd", lat: 6.935, lng: 80.058, desc: "PET, PVC, HDPE, LDPE; PVC pipes; Panagoda" },
  { name: "Orient PVC", lat: 6.963, lng: 79.907, desc: "PVC; agricultural pipes; Wellampitiya" },
  { name: "Gamini Stores", lat: 6.92, lng: 79.88, desc: "PET, PP; Borella" },
  { name: "K.O.Plastic", lat: 6.89, lng: 79.86, desc: "PET; Bambalapitiya" },
  { name: "Vishal Recycling Service", lat: 6.90, lng: 79.89, desc: "PP, HIPS, HDPE, LDPE; Ethulkotte" },
  { name: "M.M.J.Services", lat: 6.92, lng: 80.05, desc: "PP, HDPE, LDPE, iron; Ranala" },
  { name: "Chandrasiri Enterprises", lat: 6.80, lng: 79.90, desc: "Plastic barrels (PP); Piliyandala" },
  { name: "S.K.K. Recycling", lat: 6.80, lng: 80.00, desc: "PP, PS, HDPE, LDPE; Polgasowita" },
  { name: "New Janitha Enterprises", lat: 6.80, lng: 80.00, desc: "PP, ABS, HIPS, PC, HDPE, LDPE; Polgasowita" },
  { name: "D.T.Enterprises", lat: 6.84, lng: 79.90, desc: "PET, PVC, PP, HDPE, LDPE, paper, cardboard; Boralesgamuwa" },
  { name: "Neptune Paper Pvt Ltd", lat: 6.963, lng: 79.907, desc: "Paper, cardboard, cotton waste (also plastics/fabric/e-waste); Wellampitiya" },
  { name: "Eko Plasco", lat: 6.65, lng: 79.95, desc: "HDPE, LDPE, PP; material recovery; Wadduwa" },
  { name: "Eco Spindles (Private) Limited", lat: 6.85, lng: 79.95, desc: "PET bottle recycling; island-wide collections" },
  { name: "Infinity Green International (Pvt) Ltd", lat: 6.98, lng: 79.92, desc: "E-waste, plastic, wire; Kelaniya" },
  { name: "Sanasuma Recycling Center", lat: 6.72, lng: 80.06, desc: "General recycling/composting; Horana" },

  // Other Provinces / Notable
  { name: "Pearl Plastics", lat: 7.14, lng: 80.57, desc: "Plastic recycling; Gampola, Kandy Road" },
  { name: "Palitha Packaging (Pvt) Ltd", lat: 7.29, lng: 80.63, desc: "Plastic & packaging; Kandy" },
  { name: "Lackysha Polisacks", lat: 8.31, lng: 80.40, desc: "Plastic sacks/recycling; Anuradhapura" },
  { name: "Cleantech (Pvt) Ltd", lat: 6.93, lng: 79.86, desc: "Circular economy; plastic & waste" },
  { name: "INSEE Ecocycle", lat: 6.93, lng: 79.86, desc: "Hazardous/e-waste/resource recovery" },
  // Additional from older/expanded lists (many small collectors)
  { name: "House of Recycle", lat: 6.85, lng: 79.87, desc: "PVC, plastic, iron, aluminium, copper, tin; Attidiya" },
  { name: "Amana Paper Collection", lat: 6.93, lng: 79.86, desc: "Paper, cardboard; Colombo" },
  { name: "Geocycle", lat: 6.935, lng: 79.925, desc: "Paper, cardboard; Angoda" },
  // ... (CEA has 100+; see full PDF for more like Super Plastic Industries (Yakkala), Ronesha Polymer (Katana), etc.)
];