import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fafc', 
  },
  scrollContent: {
    padding: 7,
    paddingBottom: 20,
  },

 
  header: {
    alignItems: 'center',
    paddingTop: 30,
    paddingBottom: 60,
    backgroundColor: '#065f46', 
    borderBottomLeftRadius: 36,
    borderBottomRightRadius: 36,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.25,
    shadowRadius: 24,
    elevation: 16,
  },
  title: {
    fontSize: 38,
    fontWeight: '800',
    color: '#ffffff',
    letterSpacing: -0.5,
  },
  subtitle: {
    color: '#a7f3d0',
    marginTop: 8,
    fontSize: 18,
    fontWeight: '500',
    opacity: 0.9,
  },

  photoContainer: {
    alignItems: 'center',
    marginTop: -70,
    marginBottom: 22,
  },
  profileImage: {
    width: 148,
    height: 148,
    borderRadius: 74,
    borderWidth: 5,
    borderColor: '#ffffff',
  },
  cameraButton: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    backgroundColor: '#10b981',
    padding: 12,
    borderRadius: 999,
    borderWidth: 4,
    borderColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 6,
  },

  // ── Action Buttons ────────────────────────────────────────
  actionButtonsContainer: {
    alignItems: 'center',
    marginBottom: 32,
  },
  editActions: {
    flexDirection: 'row',
    gap: 16,
  },
  cancelButton: {
    backgroundColor: '#ef4444',
    paddingHorizontal: 28,
    paddingVertical: 16,
    borderRadius: 999,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  saveButton: {
    backgroundColor: '#10b981',
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 999,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    shadowColor: '#10b981',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
  },
  editProfileButton: {
    backgroundColor: '#10b981',
    paddingHorizontal: 40,
    paddingVertical: 18,
    borderRadius: 999,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    shadowColor: '#10b981',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 10,
  },
  buttonText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 17,
  },

  // ── Form Card ─────────────────────────────────────────────
  formCard: {
    backgroundColor: 'white',
    borderRadius: 28,
    padding: 28,
    marginBottom: 40,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 24,
    elevation: 10,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  inputGroup: {
    marginBottom: 28,
  },
  label: {
    color: '#065f46',
    fontWeight: '700',
    fontSize: 16,
    marginBottom: 10,
  },
  input: {
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    borderRadius: 16,
    paddingHorizontal: 20,
    paddingVertical: 18,
    fontSize: 17,
    backgroundColor: '#ffffff',
  },
  inputEditing: {
    borderColor: '#34d399',
    backgroundColor: '#f0fdfa',
    shadowColor: '#34d399',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
  },
  inputReadonly: {
    borderColor: '#d1fae5',
    backgroundColor: '#f8fafc',
    color: '#334155',
  },

  // ── Section Title ─────────────────────────────────────────
  sectionTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#065f46',
    marginBottom: 28,
    textAlign: 'center',
    letterSpacing: -0.3,
  },

  // ── Stats Cards ───────────────────────────────────────────
  statsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 20,
    justifyContent: 'center',
    marginBottom: 48,
  },
  statCard: {
    backgroundColor: 'white',
    padding: 24,
    borderRadius: 24,
    minWidth: 140,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  statValue: {
    fontSize: 36,
    fontWeight: '800',
    color: '#065f46',
    marginTop: 8,
  },
  statLabel: {
    color: '#64748b',
    marginTop: 6,
    fontSize: 15,
    fontWeight: '600',
  },
  icon: {
    color: '#10b981',
    marginBottom: 4,
  },

  // ── Logout ────────────────────────────────────────────────
  logoutButton: {
    marginTop: 16,
    backgroundColor: '#fee2e2',
    paddingVertical: 18,
    borderRadius: 999,
    alignItems: 'center',
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 6,
  },
  logoutText: {
    color: '#ef4444',
    fontWeight: '700',
    fontSize: 17,
  },
});